BackendAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: BackendAdminBundle:Default:index }

#BackendAdminBundle Profile
BackendAdminBundle_profile_index:
    pattern:  /profile
    defaults: { _controller: BackendAdminBundle:Profile:index }

BackendAdminBundle_client:
    resource: "@BackendAdminBundle/Resources/config/routing/client.yml"
    prefix:   /client

BackendAdminBundle_vols:
    resource: "@BackendAdminBundle/Resources/config/routing/vols.yml"
    prefix:   /vols

BackendAdminBundle_airoport:
    resource: "@BackendAdminBundle/Resources/config/routing/airoport.yml"
    prefix:   /airoport

BackendAdminBundle_reservation:
    resource: "@BackendAdminBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

