vols:
    pattern:  /
    defaults: { _controller: "BackendAdminBundle:Vols:index" }

vols_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendAdminBundle:Vols:show" }

vols_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Vols:new" }

vols_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Vols:create" }
    requirements: { _method: post }

vols_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Vols:edit" }

vols_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Vols:update" }
    requirements: { _method: post }

vols_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Vols:delete" }
    requirements: { _method: post }
