FrontendWebBundle_homepage:
    pattern:  /
    defaults: { _controller: FrontendWebBundle:Home:index }

FrontendWebBundle_search_result:
    pattern:  /results
    defaults: { _controller: FrontendWebBundle:Search:results }
    
FrontendWebBundle_client_subscribe:
  pattern:  /subscribe
  defaults: { _controller: FrontendWebBundle:Client:subscribe }
  
FrontendWebBundle_client_subscribe_success:
  pattern:  /subscribe/success
  defaults: { _controller: FrontendWebBundle:Client:subscribeSuccess }  